/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author laptop-02
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        super("Projekat PS - Pocetna forma");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrentUser = new javax.swing.JLabel();
        jmenuBarMain = new javax.swing.JMenuBar();
        jmenuProduct = new javax.swing.JMenu();
        jmiProductNew = new javax.swing.JMenuItem();
        jmiProductShowAll = new javax.swing.JMenuItem();
        jmenuAbout = new javax.swing.JMenu();
        jmiAboutSoftware = new javax.swing.JMenuItem();
        jmenuInvoice = new javax.swing.JMenu();
        jmiNewInvoice = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCurrentUser.setText("jLabel1");

        jmenuProduct.setText("Product");

        jmiProductNew.setText("New");
        jmenuProduct.add(jmiProductNew);

        jmiProductShowAll.setText("Show all");
        jmenuProduct.add(jmiProductShowAll);

        jmenuBarMain.add(jmenuProduct);

        jmenuAbout.setText("About");

        jmiAboutSoftware.setText("Software");
        jmenuAbout.add(jmiAboutSoftware);

        jmenuBarMain.add(jmenuAbout);

        jmenuInvoice.setText("Invoice");

        jmiNewInvoice.setText("New");
        jmenuInvoice.add(jmiNewInvoice);

        jmenuBarMain.add(jmenuInvoice);

        setJMenuBar(jmenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmenuAbout;
    private javax.swing.JMenuBar jmenuBarMain;
    private javax.swing.JMenu jmenuInvoice;
    private javax.swing.JMenu jmenuProduct;
    private javax.swing.JMenuItem jmiAboutSoftware;
    private javax.swing.JMenuItem jmiNewInvoice;
    private javax.swing.JMenuItem jmiProductNew;
    private javax.swing.JMenuItem jmiProductShowAll;
    private javax.swing.JLabel lblCurrentUser;
    // End of variables declaration//GEN-END:variables

    public void jmiProductNewAddActionListener(ActionListener actionListener) {
        jmiProductNew.addActionListener(actionListener);
    }

    public void jmiProductShowAllActionListener(ActionListener actionListener) {
        jmiProductShowAll.addActionListener(actionListener);
    }

    public JLabel getLblCurrentUser() {
        return lblCurrentUser;
    }
    
     public JMenuItem getJmiNewInvoice() {
        return jmiNewInvoice;
    }
}
